default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["DATABASE_HOST"] || 'db' %>
  username: postgres
  password: <%= ENV["PGPASSWORD"] %>
  pool: 5

development:
  <<: *default
  database: app_development


test:
  <<: *default
  database: app_test

production:
  url: <%= ENV['DATABASE_URL'] %>
